### ISSUE TITLE
onIconTap is not a function

### ISSUE THREAD

**Issue by Relax594** [ui-ninja/react-native-rating-element#16]
Running this 

`<Rating size={48} totalCount={1} rated={stern1} />`

and clicking on it crashes the app because of

`ERROR    TypeError: onIconTap is not a function. (In 'onIconTap(position + 1)', 'onIconTap' is undefined)`

There is never a check if this function exists and from reading the docs there is no need to define this function.

Please either check if the function exists (which should be the way to go anyways) or update the docs :) Thanks!

**Comment by ui-ninja** [comment]
Good catch.. Will fix and revert soon.

**Comment by ui-ninja** [comment]
Fixed. Check v5.3.2

**Comment by Relax594** [comment]
LGTM
