### ISSUE TITLE
Bug: column-reverse not working properly

### ISSUE THREAD

**Issue by pROFESOR11** [ui-ninja/react-native-rating-element#25]
Hi,
It works well with `direction="column"`, but when direction is set to `column-reverse`, the views are not aligned and coloredIcons are not drawn from bottom to up.

```
<Rating
        rated={0.5}
        totalCount={1}
        ratingColor="#f1c644"
        ratingBackgroundColor="#d4d4d4"
        size={100}
        readonly
        icon="ios-star"
        direction="column" // direction="column-reverse"
      />
```
direction="column"            |  direction="column-reverse"
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/26159043/103169870-a7849680-4850-11eb-8b36-1033846de074.png) | ![image](https://user-images.githubusercontent.com/26159043/103169906-fb8f7b00-4850-11eb-9024-e4bb2ae3defe.png)

**Comment by ui-ninja** [comment]
@pROFESOR11 Strange. Demo folder has example which uses the "column-reverse" and it works fine. Can you share parent wrapper code as well?

**Comment by pROFESOR11** [comment]
@ui-ninja Here you are:
```
export default function App() {
  return (
    <View style={styles.container}>
      <Rating
        rated={0.5}
        totalCount={1}
        ratingColor="#f1c644"
        ratingBackgroundColor="#d4d4d4"
        size={100}
        readonly // by default is false
        icon="ios-star"
        direction="column-reverse" // anyOf["row" (default), "row-reverse", "column", "column-reverse"]
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
I've also created a snack: https://snack.expo.io/@profesor/smart-orange

**Comment by ui-ninja** [comment]
Well this is what i see on snack shared.. looks fine to me

![image](https://user-images.githubusercontent.com/12812377/103789982-a3cdec80-5066-11eb-9f28-7dd74e9264a6.png)

**Comment by pROFESOR11** [comment]
@ui-ninja Could you try on iOS?

**Comment by ui-ninja** [comment]
ah! I see the issue now. Will fix and release minor patch soon

**Comment by ui-ninja** [comment]
@pROFESOR11 released a new version https://github.com/ui-ninja/react-native-rating-element/releases/tag/5.4.0
update the pkg and see if it resolves the bug? Reopen if it doesn't fix.
