### ISSUE TITLE
What about interactivity with Custom Images ?

### ISSUE THREAD

**Issue by itsroshan137** [ui-ninja/react-native-rating-element#26]

**Comment by ui-ninja** [comment]
`onIconTap` is present as prop. Refer to `demo` folder for example.

**Comment by itsroshan137** [comment]
onIconTap from left to right user is supposed to see the changes in the interactivity within the ratings itself. How can I achieve that with this library?

Being more specific I want to achieve the interactivity that you had with the heart icon || family icon (from your demo gif) but with the custom image.

**Comment by ui-ninja** [comment]
That is something you need to manage rather than the library.

Maintain a state for rating value inside your component and pass that state to <Rating rated={your_state_rating_value} ...props />

`App.js` inside Demo folder has same logic.

**Comment by itsroshan137** [comment]
Thank you so much :)
