### ISSUE TITLE
[Feature Request] Add option for vertical / horizontal rating

### ISSUE THREAD

**Issue by Relax594** [ui-ninja/react-native-rating-element#3]
Please add an option to display the rating icons vertical (going from bottom (0) to top (X))

**Comment by ui-ninja** [comment]
@Relax594 Interesting! Will check and revert with new version.

**Comment by ui-ninja** [comment]
@Relax594  Checkout new release v5.
It now will support `direction` prop to <Rating />.
Please note: `direction` prop accepts any of ['row', 'row-reverse', 'column', 'column-reverse']

[Demo](https://s7.gifyu.com/images/rating-demo-gif.gif)

**Comment by Relax594** [comment]
That was quick, holy F*! Will give it a try later today. Thank you very much!

EDIT: Working as expected, thank you! Will open up another Feature Request for something else :)
