### ISSUE TITLE
onIconTap should fire even if readonly is true

### ISSUE THREAD

**Issue by Relax594** [ui-ninja/react-native-rating-element#9]
I know it's by design, but why? I don't see any reason for it. Even if the Rating is readonly, i want to know where a user tapped (to toggle tooltips in my case).

https://github.com/ui-ninja/react-native-rating-element/blob/eafbde201a1dc06c9b2e3c3a6d79403b7049b45d/src/Rating/components/IconBar.js#L31

If you want to keep it this way, at least note it in the docs.

Regards

**Comment by ui-ninja** [comment]
I don't think it will make sense to trigger `onIconTap` if readonly is passed. For your usecase, simply don't make it readonly..

> If you want to keep it this way, at least note it in the docs.

I mentioned it under API table's row `readonly` that onPress wont be fired.. But I forgot to update it once I changed `onPress` to `onIconTap`. Will update soon in new minor version.
Anyway i have plans to make few changes in IconBar.

**Comment by Relax594** [comment]
> For your usecase, simply don't make it readonly..

haha honestly, i never thought about this :100: 

Thanks a lot!
